apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: anupam
spec:
  selector:
    app: tripviewer
  ports:
  - name: http 
    port: 80
    targetPort: tripviewer-port
  type: LoadBalancer
