apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: anupam-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      role: web
  template:
    metadata:
      labels:
        app: user
        role: web
    spec:
      containers:
      - name: user
        image: registryjrc4068.azurecr.io/anupam/user:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "2024Mi"
            cpu: "2024m"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: /api/user-java/healthcheck
            port: user-port
        envFrom:
          - configMapRef:
              name: dbconfig
        ports:  
        - name: user-port
          containerPort: 80
