apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "dave" to read secrets in the "development" namespace.
# You need to already have a ClusterRole named "secret-reader".
kind: RoleBinding
metadata:
  name: web-role-bindings
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "development" namespace.
  namespace: anupam-web
subjects:
- kind: Group
  name: 5cc4449e-0329-49c5-9fc6-1422685fddbd # Name is case sensitive
  namespace: anupam-web
roleRef:
  kind: Role
  name: web-admin
  apiGroup: rbac.authorization.k8s.io