apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: anupam-web
  name: web-admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log", "configmaps","services", "endpoints", "deployments"]
  verbs: [ "list", "watch" ]
