apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: anupam-api
spec:
  selector:
    app: trips
  ports:
  - name: http 
    port: 80
    targetPort: trips-port
  type: ClusterIP
