apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: anupam-api
  labels:
    aadpodidbinding: anupam-pod-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      volumes:
        - name: secrets-mount
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault"
      containers:
      - name: poi
        image: registryjrc4068.azurecr.io/anupam/poi:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: /api/poi/healthcheck
            port: poi-port
        env:
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sqlcredentials
                key: SQLSERVER
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqlcredentials
                key: SQLUSER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlcredentials
                key: SQLPASSWORD
        ports:  
        - name: poi-port
          containerPort: 80
        volumeMounts:
        - name: secrets-mount
          mountPath: "/mnt/secrets-store"

