apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: anupam-api
spec:
  provider: azure                             
  secretObjects:                   
  - data:
    - key: SQLSERVER
      objectName: SQLSERVER
    - key: SQLPASSWORD
      objectName: SQLPASSWORD
    - key: SQLUSER
      objectName: SQLUSER
    secretName: sqlcredentials    
    type: Opaque   
  parameters:
    keyvaultName: anupamvault
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 41077fd5-7212-4868-941d-3d950c3dc65c
    cloudName: ""
    objects: |
      array:
      - |
        objectName: SQLSERVER # In this example, 'ExampleSecret'
        objectType: secret # Object types: secret, key or cert
        objectVersion: "" # [OPTIONAL] object versions, default to latest if empty
      - |
        objectName: SQLUSER # In this example, 'ExampleSecret'
        objectType: secret # Object types: secret, key or cert
        objectVersion: "" # [OPTIONAL] object versions, default to latest if empty
      - |
        objectName: SQLPASSWORD # In this example, 'ExampleSecret'
        objectType: secret # Object types: secret, key or cert
        objectVersion: "" # [OPTIONAL] object versions, default to latest if empty  
    tenantId: a038cd8f-3946-4703-ba91-4996cbb34b76
